[tool.poetry]
name = "karp-tng-backend"
version = "0.8.1"
license = "MIT"
description = "Karp backend"
readme = "README.md"
authors = [
	"Språkbanken at the University of Gothenburg <sb-info@svenska.gu.se>",
]
homepage = "https://spraakbanken.gu.se"

documentation = "https://github.com/spraakbanken/karp-tng-backend"
repository = "https://github.com/spraakbanken/karp-tng-backend"
classifiers = [
	"Development Status :: 2 - Pre-Alpha",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: MIT License",
	"Operating System :: Unix",
	"Operating System :: POSIX",
	"Operating System :: Microsoft :: Windows",
	"Topic :: Utilities",
]
packages = [{ include = "karp" }]

[tool.poetry.scripts]
karp-cli = "karp.cliapp.main:cliapp"
# ; karp.modules =
# ;     health = "karp.webapp.health"_api
# ;     entries = "karp.webapp.views.entries"
# ;     resources = "karp.webapp.resources"_api
# ; 	history = "karp.webapp.views.history"
# ; 	stats = "karp.webapp.stats"_api
# ; 	query = "karp.webapp.query"_api
[tool.poetry.plugins."karp.infrastructure"]
"es6" = "karp.infrastructure.elasticsearch6"
"sql" = "karp.infrastructure.sql"
"testing" = "karp.infrastructure.testing"
"jwt" = "karp.infrastructure.jwt"
[tool.poetry.plugins."karp.clicommands"]
"entries" = "karp.cliapp.subapp"
"resource" = "karp.cliapp.subapp"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/spraakbanken/karp-tng-backend/issues"

[tool.poetry.dependencies]
python = "^3.8"
json-streams = "^0.10.1"
paradigmextract = "^0.1.1"
pydantic = "^1.8.2"
PyJWT = "^2.1.0"
sb-json-tools = "^0.9.1"
SQLAlchemy = "^1.4.25"
sqlalchemy-json = "^0.4.0"
SQLAlchemy-Utils = "^0.37.8"
tabulate = "^0.8.9"
tenacity = "^8.0.1"
tqdm = "^4.62.3"
typer = "^0.4.0"
urllib3 = "^1.26.7"
uvicorn = "^0.15.0"
fastapi = "^0.68.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
autopep8 = "^1.5.7"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
mypy = "^0.910"
bump2version = "^1.0.1"
factory-boy = "^3.2.0"
requests = "^2.26.0"
isort = "^5.9.3"
flakehell = "^0.9.0"
wemake-python-styleguide = "^0.15.3"
