[tool.poetry]
name = "karp-tng-backend"
license = "MIT"
description = "Karp backend"
readme = "README.md"
authors = ["Språkbanken at the University of Gothenburg<sb-info@svenska.gu.se>"]
homepage = "https://spraakbanken.gu.se"

documentation = "https://github.com/spraakbanken/karp-tng-backend"
repository = "https://github.com/spraakbanken/karp-tng-backend"
classifiers = [
	"Development Status :: 2 - Pre-Alpha",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: MIT License",
	"Operating System :: Unix",
	"Operating System :: POSIX",
	"Operating System :: Microsoft :: Windows",
	"Topic :: Utilities",
]
packages = [
	{ include = "karp" },
]

[tool.poetry.scripts]
karp-cli = "karp.cliapp.main:cliapp"
; karp.modules =
;     health = "karp.webapp.health"_api
;     entries = "karp.webapp.views.entries"
;     resources = "karp.webapp.resources"_api
; 	history = "karp.webapp.views.history"
; 	stats = "karp.webapp.stats"_api
; 	query = "karp.webapp.query"_api
karp.infrastructure =
	es6 = "karp.infrastructure.elasticsearch6"
    sql = "karp.infrastructure.sql"
	testing = "karp.infrastructure.testing"
	jwt = "karp.infrastructure.jwt"
karp.clicommands =
    entries = "karp.cliapp.subapp"_entries
	resource = "karp.cliapp.subapp"_resource

[tool.poetry.urls]
"Bug Tracker"" = "https://github.com/spraakbanken/karp-tng-backend/issues"

[extras]
elasticsearch6 =
	elasticsearch>=6,<7.0.0
	elasticsearch-dsl>=6,<7.0.0
elasticsearch7 =
	elasticsearch>=7,<8.0.0
	elasticsearch-dsl>=7,<8.0.0
dev =
	pysqlcipher3
	flake8
	elasticsearch-test-py
	pylint
	pytest
	pytest-cov
	pyre-check
	python-dotenv
	bump2version
	black
	mypy
	bandit
    factory-boy
	requests
	isort
mysql =
	pymysql
	mysqlclient

[tool.pytest]
testpaths = "karp/tests"
junit_family = "xunit1"

[tool.coverage.run]
branch = true
source =
	karp
omit =
	karp/tests/*

[pycodestyle]
max-line-length = "120"

[flake8]
max-line-length = "120"

# slack-log-utils
#mysqlclient
#starlette
alembic
click
cryptography>=3.3.2
dependency-injector
elasticsearch-dsl>=6,<7.0.0
elasticsearch>=6,<7.0.0
environs
fastapi
fastjsonschema
gunicorn
importlib_metadata; python_version < "3.8"
json_streams
paradigmextract>=0.1.0
pydantic
pyjwt
sb-json-tools>=0.5.2
sqlalchemy
sqlalchemy-json
sqlalchemy-utils
tabulate
tenacity
tqdm
typer
urllib3>=1.26.5
uvicorn
