[tool.poetry]
name = "karp-backend"
version = "6.0.22"
license = "MIT"
description = "Karp backend"
readme = "README.md"
authors = [
	"Språkbanken at the University of Gothenburg <sb-info@svenska.gu.se>",
]
homepage = "https://spraakbanken.gu.se"

documentation = "https://github.com/spraakbanken/karp-backend"
repository = "https://github.com/spraakbanken/karp-backend"
classifiers = [
	"Development Status :: 4 - Beta",
	"Intended Audience :: Developers",
	"License :: OSI Approved :: MIT License",
	"Operating System :: Unix",
	"Operating System :: POSIX",
	"Operating System :: Microsoft :: Windows",
	"Topic :: Utilities",
]
packages = [{ include = "karp" }]

[tool.poetry.scripts]
karp-cli = "karp.cliapp.main:cliapp"
# ; karp.modules =
# ;     health = "karp.webapp.health"_api
# ;     entries = "karp.webapp.views.entries"
# ;     resources = "karp.webapp.resources"_api
# ; 	history = "karp.webapp.views.history"
# ; 	stats = "karp.webapp.stats"_api
# ; 	query = "karp.webapp.query"_api
[tool.poetry.plugins."karp.infrastructure"]
"es6" = "karp.infrastructure.elasticsearch6"
"sql" = "karp.infrastructure.sql"
"testing" = "karp.infrastructure.testing"
"jwt" = "karp.infrastructure.jwt"

# [tool.poetry.plugins."karp.clicommands"]
# "db" = "karp.cliapp.subapp_database"
# "entries" = "karp.cliapp.subapp_entries"
# "entry_repo" = "karp.cliapp.subapp_entry_repo"
# "resource" = "karp.cliapp.subapp_resource"
# "query" = "karp.cliapp.subapps.query_subapp"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/spraakbanken/karp-backend/issues"

[tool.poetry.dependencies]
python = "^3.10"
json-streams = "^0.12.0"
paradigmextract = "^0.1.1"
pydantic = "^1.10.2"
PyJWT = { version = "^2.4.0", extras = ["crypto"] }
sb-json-tools = "^0.9.1"
SQLAlchemy = "^1.4.25"
sqlalchemy-json = "^0.5.0"
SQLAlchemy-Utils = "^0.38.3"
tabulate = "^0.8.10"
tenacity = "^8.0.1"
tqdm = "^4.62.3"
typer = "^0.6.1"
urllib3 = "^1.26.7"
fastapi = "^0.85.0"
injector = "^0.20.1"
alembic = "^1.8.1"
regex = "^2022.8.17"
python-dotenv = "^0.19.0"
environs = "^9.3.4"
elasticsearch = "^6"
elasticsearch-dsl = "^6"
mysqlclient = { version = "^2.1.1", optional = true }
TatSu = "^5.8.3"
PyMySQL = { version = "^1.0.2", optional = true }
aiosqlite = { version = "^0.17.0", optional = true }
aiomysql = { version = "^0.1.1", optional = true }
asgi-correlation-id = "^3.0.1"
python-json-logger = "^2.0.4"
ulid-py = "^1.1.0"
Deprecated = "^1.2.13"

[tool.poetry.extras]
mysql = ["mysqlclient", "PyMySQL", "aiomysql"]
sqlite = ["aiosqlite"]

[tool.poetry.dev-dependencies]
uvicorn = "^0.18.3"
pytest = "^7.1.3"
pytest-cov = "^3.0.0"
mypy = "^0.971"
bump2version = "^1.0.1"
factory-boy = "^3.2.1"
isort = "^5.10.1"
cryptography = "^38.0.1"
types-tabulate = "^0.8.11"
vulture = "^2.5"
pylint = "^2.15.2"
black = "^22.8.0"
elasticsearch-test-py = "^1.1.0"
requests = "^2.28.1"
mkdocs = "^1.3.1"
mkdocs-material = "^8.5.6"
mkdocstrings = "^0.19.0"
mkdocstrings-python = "^0.7.1"

[tool.vulture]
exclude = ["karp/tests/"]
min_confidence = 100
paths = ["karp"]
ignore_decorators = ["@abc.abstractmethod"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
