name: Build

on: [push]

jobs:
  checks:
    name: ${{ matrix.task.name }} py-${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest]
        task:
          - name: Lint w pylint
            run: make lint
            allow_failure: true
          # - name: Lint w bandit
          #   run: make lint-security-issues
          #   allow_failure: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install dependencies
        run: make install-dev

      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.run }}
        continue-on-error: ${{ matrix.task.allow_failure }}
        env:
          DB_DRIVER: sqlite

  unit-tests:
    name: ${{ matrix.task.name }} py-${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest]
        task:
          - name: Unit tests
            run: make unit-tests-w-coverage
            allow_failure: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install dependencies
        run: make install-dev

      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.run }}
        continue-on-error: ${{ matrix.task.allow_failure }}
        env:
          DB_DRIVER: sqlite
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage1.xml,./coverage2.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

  tests:
    name: ${{ matrix.task.name }} py-${{ matrix.python-version }} es-${{ matrix.es.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    services:
      mysql:
        image: mariadb:10.3
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: testing
          MYSQL_DATABASE: karp
          MYSQL_PASSWORD: testing
          MYSQL_USER: karp
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        es:
          - use: false
            version: NO
          - use: true
            version: 6.8.23
        os: [ubuntu-latest]
        task:
          - name: Integration tests
            run: make integration-tests-w-coverage
          - name: End-to-end tests
            run: make e2e-tests-w-coverage
        exclude:
          - es:
              use: false
            task:
              name: End-to-end tests

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install dependencies
        run: |
          make install-dev
          make install-dev-mysql
          cp -v .env.ci .env

      - name: Install Elasticsearch 6
        if: startsWith( matrix.es.version, '6')
        run: |
          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${{ matrix.es.version }}.tar.gz
          tar -xzf elasticsearch-${{ matrix.es.version }}.tar.gz
          ./elasticsearch-${{ matrix.es.version }}/bin/elasticsearch-plugin install analysis-icu
          echo "TEST_ELASTICSEARCH_ENABLED=True" >> .env
          echo "TEST_ES_HOME=`realpath elasticsearch-${{ matrix.es.version }}`" >> .env
          echo "SEARCH_CONTEXT=es6_search_service" >> .env
          cat .env
          # make install-dev-elasticsearch6
          # pip install -e .[elasticsearch6]

      - name: Install Elasticsearch 7
        if: startsWith( matrix.es.version, '7')
        run: |
          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${{ matrix.es.version }}-linux-x86_64.tar.gz
          tar -xzf elasticsearch-${{ matrix.es.version }}-linux-x86_64.tar.gz
          echo "TEST_ELASTICSEARCH_ENABLED=True" >> .env
          echo "TEST_ES_HOME=`realpath elasticsearch-${{ matrix.es.version }}`" >> .env
          cat .env
          pip install -e .[elasticsearch7]
          #- name: Setup sql index
          #if: ! ${{ matrix.es.use }}
          #run: echo "SEARCH_CONTEXT=sql_index" >> .env
      - name: List tree
        run: tree .
      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.run }}
        env:
          DB_TEST_DATABASE: karp
          DB_USER: karp
          DB_PASSWORD: testing
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage1.xml,./coverage2.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
